### ISSUE TITLE
When running start command from palette, I received this error

### ISSUE THREAD

**Issue by Shine18** [Negative-Space-Dev/code-sense#3]
<img width="686" alt="image" src="https://github.com/Negative-Space-Dev/code-sense/assets/6214437/fa99249b-c75e-4589-8e6b-d2c12afbc947">

**Comment by JasonHassold** [comment]
Hey @Shine18!

I've had this issue a couple of times during the development of codesense, but not typically when just using it. I'm pretty sure it just means that an instance is already running likely because it didn't exit correctly.

If you are using linux or mac you should be able to use `sudo lsof -i :49168` to find the process ID and then `kill PID` to stop that process. Then just restart codesense.

It's possible there is more to it but let me know if that works or not.

**Comment by Shine18** [comment]
I think these are other applications using this port. 
<img width="1204" alt="image" src="https://github.com/Negative-Space-Dev/code-sense/assets/6214437/84570954-1c54-4182-9424-08d896e23153">

**Comment by JasonHassold** [comment]
Ahh gotcha, that makes sense too, should be a pretty easy fix. I don't have time right now but I'll let you know once I have time to fix this.

**Comment by Shine18** [comment]
Sure Jason
Thank you so much.
Maybe a setting for the port configuration would be good.

**Comment by JasonHassold** [comment]
@Shine18 I just pushed up a new version that contains the updates to fix this. Just install the new version and go to your preferences. I added a config setting "Server Port" under "CodeSense" that you can use to set the port, just don't forget to Reload VSCode for the change to take effect.

**Comment by Shine18** [comment]
Thanks @JasonHassold 
Awesome support. I will update on my side.
